### ISSUE TITLE
Sums only for actually displayed cards

### ISSUE THREAD

**Issue by torstenweber** [CampbellMG/Trello-Powerups#8]
Thank you for the Sum Power-up!

One improvement would be to calculate the sums only for the cards that are _actually displayed_ in a list. Currently, the sums are always calculated for _all_ cards in a list, regardless of whether they are filtered or not.

**Comment by CampbellMG** [comment]
Hi Torsten,

Thanks for getting in touch. I do definitely agree that this change would make the power-up more intuitive. However, I'm having a hard time finding any method of implementing this filter within the power-up.

As you can see in this model below, there isn't any data that can be used to determine if the card is currently visible on the board. I've trying to find out if it's actually possible in the Developer Community and will keep you up to date.

![Screenshot 2022-07-22 114055](https://user-images.githubusercontent.com/40409896/180344897-ede802b6-d2d4-4324-b2f5-9968bfd76dae.png)

**Comment by CampbellMG** [comment]
Unfortunately, after checking with the Atlassian dev community, this request isn't possible as the card filtering is handled locally in the browser.

https://community.developer.atlassian.com/t/accessing-current-filters-in-power-up/60068/3
